export const Colors = {

  BACKGROUND: '#000',
  TEXT_COLOR: '#ffffff',
  ICON_COLOR: '#efefef',
  BUBBLE_SELF: '#6D31FF',
  BUBBLE_SELF_BORDER: '#4919BD',
  TRANSPARENT_COLOR: 'transparent',
  WHITE_COLOR: '#FFFFFF',
  DELETE_COLOR: '#FF6370',
  BORDER_COLOR: '#2e2f48',
  BORDER_BOTTOM: '#444444',
  BACK_COLOR: '#E5E5E5',
  TITLE_COLOR: '#121A24',
  DATE_COLOR: '#66688F',
  LIGHT_GRAY_COLOR: '#C7C7CC',
  PRIMARY_LIGHT_COLOR: '#007AFF',

};
